dist: xenial
language: go

services:
  - docker

go:
  - 1.15.x
  - 1.14.x
  - master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

go_import_path: github.com/percona/proxysql_exporter

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  global:
    - secure: "w5CuQ8yiQ1U/zhHJ0SjiXkYGu/5AAYgWf7x3x+VkDnzOW2mXS/JiE9RKDMbVFd+wGr0OdFpVMB4NQVQBVLwafPtEHQsMrRaQTf6puHHNwlXoFKnzqF9adtpRId/8aGfbT+PbNsW4dtIAimlaKr48kmmImD/196Ef0RvVBj2oLurOzlDWErC2xdvPyC7E68y54gLD4OXrSr7f4KVPeJ4usbcqr8qc5OqlFyURL5gRPiDUl4BUkLXrmlk4huLMa1Z3xf5YcghPd5h4aF15gnBNJK4Cn3ZW1XX6Rm5/MVuOfUuTfBtm75I76qT4O1PD7SoekH2N5fldLPd5et2IyuPIsEjsC9tAajzeQeazWr52brntcdJuz4aaYbACjup8tpTHsefWILbvoR9Avpe0P2cNKarxkYNJ8HxzujTmxG7N1Wruu/1Cd3jKfWQDYCw40/AFkSb2QIVsCLCe4vjqVTCNRanYmbcxL47tQuT4yjHCVdQ9IHE7N/abvOeNFxk93aeH+bqRQfrxLfQm+FD6js40axfocwL4uP8b3EmxfoTEyvSPofyhnKMd6OUOUIt9mgQj1RPqFnoPHzodRWqBhQ/86DaK8ZSGYqgivddbjr0bSBu/SbV/Ig4L4MgNXuYu30FXXzvXLfZNO+uz95QsQeYqfe1lmQZVhpiCs4In8BGgH+4="
  matrix:
    - PROXYSQL_IMAGE=percona/proxysql:1.2.1
    - PROXYSQL_IMAGE=perconalab/proxysql:1.3.6
    - PROXYSQL_IMAGE=percona/proxysql:2.0.14

install:
  # install reviewdog and golangci-lin
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

before_script:
  # static analyze
  - bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
  - bin/golangci-lint run -c=.golangci.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make format build testall

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: RJipNzbg9ypZfIGFyfSQSGh4XFh1psVs8hKr7HAK3pwFl1lSaoErjxHgNA7zrQ+G3z1CyCx6McPAjJG8pcijCJVV8TAikVNJmW3kp5BA7X4agi24/tUOzkiATLf+O6SyTn22NUe3INTxJx7mYBvA3YlOaMobBFT1eBFFl4niekIwilrBWQOdHRZ8GjvTUrd/vLse7mP5OwMDEr8hnKnjX4FNKhORk8iopU/l3V+Po6veBiKbNVK5cn6XQ3Xnw/d3gMX+YOw2B5EMAchloLg85G+HawpjjYs4PDBcVQVYX8fwVhkGcyl1cStQ97aE8t5L3qPXPVgeNQnbViPsXzQ1lbcnd1l7ST+HPBR6Dkr0mTRophbMWgizsldnUiTeSYzjN9NIT3INCleofycCy2+Aasqdfi5BWMy5L07bLs98VWTJq38fdwCACgS1Btyl/wAqkp12PHDw51bg6B4un0tEEG8ySB3jI0Flo+XCTIUK8Oc+rQCRiQiN5AqT6eDtrEiIGmN9Tj1xGp4Znf6GhZssR/nAO5VH5G9kwVXUUUJy6UJ0Qe63KwSUROjauNTFBpwvKlXvxcup03ZoxJ3Wmg6fcTe9/HvhA7ocx3EkiPsuKHcur8/6W+aiKLCeiUUtq1WcUv2p2w21o3jyQ0KjG3gBJqq3KWrjW6ArATHCnK6DCQs=
